[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"

remappings = ["ds-test/=lib/forge-std/lib/ds-test/src/",
            "forge-std/=lib/forge-std/src/",
            "v2-periphery/=lib/v2-periphery/contracts/",
            "v3-core/=lib/v3-core/contracts/"]